# configuration file for vector map factory

MAP_NAME="slazav_fi"
MAP_ATTR="http://slazav.xyz/maps/"

MS2RENDER="/home/sla/mapsoft2/programs/ms2render/ms2render -v"

VMAP_DIR=vmap;
VMAP_EXT=vmap2; # Extension/format of vector maps
NOM_MAG=1;      # Scaling of maps. Use NOM_MAP=2 for 1km sheets with 500m maps
DPI_MAP=100;
DPI=200;
DPI_PR=150;
STYLE_HR=1;
FIG_ENC=UTF-8;

CMAP=cmap.png;  # Colormap
CMAP_SRC=r34-101,102;   # colormap source

REND_CFG=render.cfg;  # Render configuration
TYPEINFO=types.cfg;    # Type information

SQLITEDB=$OUT_DIR/slazav_fi.sqlitedb;
MBTILES=$OUT_DIR/slazav_fi.mbtiles;
IMGMAP=$OUT_DIR/slazav_fi.img;

TILE_DIR=
TLIST=;
TILE_MAXZ=13;  # max z-index
TILE_MAXE=6    # max index for empty map

GRID=1



function vmap_render_map() {
  ifile=$1
  name=$2
  png=$3
  map=$4
  title=$5
  dpi=${6:-$DPI}
  nom=${name%s}
  [ "$nom" = "$name" ] && sc="" ||  sc="--obj_scale 0.666667"

  $MS2RENDER $ifile --out "$png"\
    $BRD_DIR/*.gpx --trk_draw_transp 0.5 --trk_draw_dots 0 --trk_draw_width 3\
    --config "$REND_CFG" -t "$TYPEINFO" --define "$(vmap_defs "$nom")" $sc\
    --mkref nom --north --name "$nom" --dpi "$dpi" --margins 10 --top_margin 30\
    --title "$title" --title_size 20\
    --cmap_load "$CMAP" --png_format pal ${map:+--map $map}
}

function vmap_render_tiles() {
  name=$1
  brd=$2
  vmap=$VMAP_DIR/$name.$VMAP_EXT
  nom=${name%s}
  [ "$nom" = "$name" ] && sc="" ||  sc="--obj_scale 0.666667"
  $MS2RENDER $vmap\
    --config "$REND_CFG" -t "$TYPEINFO" --define "$(vmap_defs "$nom" clip)"\
    --tmap --add --out "$TILE_DIR/{x}-{y}-{z}.png" $sc\
    --zmin 0 --zfill $TILE_MAXE --zmax $TILE_MAXZ --fillcolor 0xFFBF6000\
    --png_format pal --cmap_load $CMAP\
    --border_file $brd\
    --tmap_scale 1 --fit_patt_size;\
}

function vmap_render_mbtiles() {
  name=$1
  brd=$2
  vmap=$VMAP_DIR/$name.$VMAP_EXT
  nom=${name%s}
  [ "$nom" = "$name" ] && sc="" ||  sc="--obj_scale 0.666667"

  $MS2RENDER $vmap\
    --config "$REND_CFG" -t "$TYPEINFO" --define "$(vmap_defs "$nom" clip)"\
    --add --out "$MBTILES" $sc\
    --zmin 0 --zfill $TILE_MAXE --zmax $TILE_MAXZ --fillcolor 0xFFBF6000\
    --png_format pal --cmap_load $CMAP\
    --border_file $brd\
    --tmap_scale 1 --fit_patt_size;\
}

function vmap_render_mp() {
  name=$1
  nom=${name%s}
  mp=$2
  mp_id=$3
  vmap="$VMAP_DIR/$name.$VMAP_EXT"
  $MS2VMAP "$vmap" -o "$mp"\
    -t "$TYPEINFO" --define "$(vmap_defs "$nom")"\
    --mp_name "$nom" --mp_id "$mp_id" --crop_nom "$nom"
}
