# configuration file for vector map factory

MAP_NAME="slazav_fi"
MAP_ATTR="http://slazav.xyz/maps/"

MS2RENDER="/home/sla/mapsoft2/programs/ms2render/ms2render -v"

VMAP_DIR=vmap;
VMAP_EXT=vmap2; # Extension/format of vector maps
NOM_MAG=1;      # Scaling of maps. Use NOM_MAP=2 for 1km sheets with 500m maps
DPI_MAP=100;
DPI=200;
DPI_PR=150;
STYLE_HR=1;
FIG_ENC=UTF-8;

CMAP=cmap.png;  # Colormap
CMAP_SRC=R34-101,102;   # colormap source

REND_CFG=render.cfg;  # Render configuration
TYPEINFO=types.cfg;    # Type information

SQLITEDB=$OUT_DIR/slazav_fi.sqlitedb;
MBTILES=$OUT_DIR/slazav_fi.mbtiles;
IMGMAP=$OUT_DIR/slazav_fi.img;

TILE_DIR=
TLIST=;
TILE_MAXZ=13;  # max z-index
TILE_MAXE=6    # max index for empty map

GRID=1


