MOD_SOURCES := lib.cpp poly_cuts.cpp
MOD_HEADERS := lib.h poly_cuts.h
PROGRAMS :=\
  import_fi1 import_fi2 import_no import_se make_nom update_map\

#  map_brd find_object\
#  make_map update_map\
#  vmap_diff\
#  test

MODDIR := /home/sla/mapsoft2/modules
include $(MODDIR)/Makefile.inc
