#!/bin/sh -efu

# Assemble final vmap file using src, patch, labels

for i in "$@"; do
  map=${i%.*}
  nom=${map%s}

  vmap="$map.vmap2"
  src="../vmap_src/$nom.vmap2.gz"
  patch="../vmap_patches/$map.patch"
  labels="../vmap_labels/$map.labels.vmap2"
  add="$map.add.vmap2"
  fig=$map.fig

  [ -f "$add" ] || add=""
  [ -f "$labels" ] || labels=""
  [ -f "$patch" ] || echo "include common.patch" > "$patch"


  # Assemble vmap
  ../progs/update_map -t ../types.cfg --patch "$patch" --apply "$src" $labels $add -o "$vmap"

  # Update fig if it exists -- duplicated at xfig_put
#  if [ -f "$fig" ]; then ./xfig_get "$map"; fi

done
